### ISSUE TITLE
请问可以推荐一本同类型的学习springd的书吗？

### ISSUE THREAD

**Issue by Liugenhao-gh** [1802802/SpringInAction5h_TacoCloud#1]
我最近也在学习《sping实战5》，我还买了实体书，可是学起来太痛苦了。当我学到第三章jpa时候，我发现代码已经跑不起来了，甚至我下载了作者源代码都无法运行。然后我又找到它的第六版，勉强看到第6章，发现代码又运行不起来了。这作者的书学起来太痛苦了。请问是否有这种同样类型，可以边写个小项目，边学习sping的书籍吗？希望您能推荐一下，谢谢您

**Comment by 1802802** [comment]
其实《Spring实战4》就满足你的全部需求，不过现在这个旧版的实体书不太好买，可以去网上找下资源很多的。
然后这个作者之前的版本写的都挺不错，不过在第五版撰写忘了初心，从娓娓道来的讲述变成了自嗨，只能说很可惜，Spring实战第五版的很多概念，起码需要3年的工作经验才能得心应手，对初学者来说确实难度太大了，不是你自己的问题。

**Comment by Liugenhao-gh** [comment]
我明白了，谢谢您的回应，提前祝您春节快乐。
